name: 'Install and build the Ruby gem'

description: 'Install Ruby dependencies and build the native extension.'

runs:
  using: "composite"
  steps:
    - name: Install Ruby dependencies
      shell: bash
      run: bundle install
